apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashing-service
  template:
    metadata:
      labels:
        app: hashing-service
    spec:
      containers:
        - name: hashing-service
          imagePullPolicy: Always
          image: ghcr.io/mkamadeus/hashing-service:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
