apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hashing-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hashing-service
  minReplicas: 1
  maxReplicas: 10
